namespace: monitoring

resources:
- namespace.yaml
- fluent-bit-geneva-logging.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml

configMapGenerator:
- envs:
  - mdsd/mdsd.env
  files:
  - mdsd/mdsd
  - mdsd/mdsd.xml
  - mdsd/mdsautokey.cfg
  name: mdsd-config
- files:
  - fluent-bit/fluent-bit.conf
  - fluent-bit/input-kubernetes.conf
  - fluent-bit/input-node-metrics.conf
  - fluent-bit/filter-kubernetes.conf
  - fluent-bit/output-mdsd.conf
  - fluent-bit/parsers.conf
  name: fluent-bit-config

secretGenerator:
- files:
  - gcscert.pem
  - gcskey.pem
  name: mdsd-certificates

generatorOptions:
  disableNameSuffixHash: true
